### ISSUE TITLE
Comment on "The Core API", section "Replication"

### ISSUE THREAD

**Issue by johannesjh** [oreilly/couchdb-guide#369]
<code>
curl -vX POST http://127.0.0.1:5984/_replicate -d '{"source":"albums","target":"albums-replica"}'
</code>

I get 
<code>{"error":"bad_content_type","reason":"Content-Type must be application/json"}</code>
 in response.

I need to add the -H "Content-Type: application/json" header to get the request working.
<code>
curl -v -H "Content-Type: application/json" -X POST http://127.0.0.1:5984/_replicate -d '{"source":"albums","target":"albums-replica"}'
</code>

**Comment by janl** [comment]
Fixed

**Comment by ThoughtCrhyme** [comment]
Encountered same problem here: http://guide.couchdb.org/editions/1/en/api.html using firefox.

**Comment by Ninerian** [comment]
The wrong curl request is still present in the german version.
